[package]
name = "rfc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
clio = "0.3.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
